nd213 capstone (#91)
* Prepare container

* Add starter code

* Add required library

* Write a readme draft

* Use angle bracket to include SDL

* Read configuration from file

* Write function document

* Apply doxygen style to the comment

* Set hierarchy to Snake

* Add food and poison class

* Add control thread

* Resolve compile error
```
cannot open source file "SDL.h"
```

* Use efficient argument passing

* Resolve compile error

```
cannot open source file "SDL.h"
```

* Copy for the first submission

* Add poison

* Resolve compile error on Workspace
```
/usr/bin/ld: CMakeFiles/SnakeGame.dir/src/game.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/SnakeGame.dir/build.make:143: recipe for target 'SnakeGame' failed
make[2]: *** [SnakeGame] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/SnakeGame.dir/all' failed
make[1]: *** [CMakeFiles/SnakeGame.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```