nd0013 3d-object-detection (#77)
* Prepare container

* Fix home location issue

* Add required packages

* Enable X11 forwarding

* Resolve opencv error

* Enable glxgears at local terminal

* Add starter code

* Adjust container for the project

* Complete step 2

* Complete ID_S3_EX1

* Fix incorrect type of ndarray

Traceback (most recent call last):
  File "/home/loop_over_dataset.py", line 208, in <module>
    tools.show_objects_in_bev_labels_in_camera(detections, lidar_bev, image, frame.laser_labels, valid_label_flags, camera_calibration, configs_det)
  File "/home/misc/objdet_tools.py", line 387, in show_objects_in_bev_labels_in_camera                                                                              project_detections_into_bev(bev_map, detections, configs)                     File "/home/misc/objdet_tools.py", line 237, in project_detections_into_bev
    cv2.line(bev_map, (corners_int[0, 0], corners_int[0, 1]), (corners_int[3, 0], corners_int[3, 1]), (255, 255, 0), 2)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:                                                   >  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

* Complete ID_S3_EX2

* Use correct index for intensity

* Complete ID_S4_EX1

* Fix incorrect box drawing on bev

* Complete ID_S4_EX2 & ID_S4_EX3

* Add screenshot on performance measure